//
// Params for block9 (Matrix City / Small_City_LVL).
// Auto-generated by run_block9_mvs_to_plan.sh — do not edit by hand.
//
// Scene:  ~745 m x 390 m, building heights ~10-100 m
// Camera: 960x540, HFOV=45 deg, VFOV=26.23 deg
//
#ifndef FUXIAN_PARAMS_H
#define FUXIAN_PARAMS_H
#define M_PI 3.1415926

namespace Params{
    const std::string SAMPLE_FILE_PATH = "data/block9_samples.ply";
    const std::string MESH_FILE_PATH   = "data/block9_mesh.ply";

    // Wider range than Town01 to handle Matrix City skyscrapers (10-100 m)
    const float MIN_DISTANCE_BETWEEN_POINT_AND_VIEW = 25;
    const float MAX_DISTANCE_BETWEEN_POINT_AND_VIEW = 50;

    // 10 deg/step horizontal sampling (36 directions, same as Town01)
    const float PER_RADIAN = 360 / 36.0 / 180.0 * M_PI;

    const int POP_SIZE = 50;
    const int TOTAL_VIEW_NUMS = 3937;

    // 10 m voxel grid for viewpoint candidates
    const float VOXEL_SIZE = 10.0f;

    // 300 m: allows cross-block visibility in the 745 m wide scene
    const float MAX_D = 300;

    const float BEST_DISTANCE = 35;
    const float THETA_T = M_PI / 3.0f;
    const bool USE_PAPER_FOV_MARK = true;

    // Camera: 960x540, HFOV=45 deg
    // VFOV = 2*atan(tan(22.5 deg)*540/960) = 26.23 deg
    const double RESOLUTION_H = 960;
    const double RESOLUTION_V = 540;
    const double FOV_H        = 45.0;
    const double FOV_V        = 26.23;
}

#endif //FUXIAN_PARAMS_H
