//
// Params for CARLA Town01 experiment.
// Copy to Params.h before building:
//   cp code/utils/Params_town01.h code/utils/Params.h
//
// Town01 scene dimensions: ~500 m × 400 m
// Building heights:         ~5–20 m
// Camera viewing distance:  25–35 m from sample points (same as xuexiao)
// Camera altitude:          30–60 m AGL (determined per viewpoint)
//
#ifndef FUXIAN_PARAMS_H
#define FUXIAN_PARAMS_H
#define M_PI 3.1415926

namespace Params{
    // --- Data paths (generated by generate_town01_ply_from_carla_scene.py) ---
    const std::string SAMPLE_FILE_PATH = "data/town01_samples.ply";
    const std::string MESH_FILE_PATH   = "data/town01_mesh.ply";

    // --- Viewpoint candidate distances ---
    // Keep same as xuexiao: 25–35 m gives good oblique coverage
    const float MIN_DISTANCE_BETWEEN_POINT_AND_VIEW = 25;
    const float MAX_DISTANCE_BETWEEN_POINT_AND_VIEW = 35;

    // Angular step for horizontal sampling (10° per step, 36 steps = 360°)
    const float PER_RADIAN = 360 / 36.0 / 180.0 * M_PI;

    // --- EA population size ---
    // 50 individuals: Town01 is larger so we trade population diversity
    // for faster iteration.  Increase to 100 if you have time.
    const int POP_SIZE = 50;

    // Maximum number of viewpoints that can appear in a single individual.
    // Set to num_samples; adjusted after PLY generation.
    const int TOTAL_VIEW_NUMS = 2000;

    // Voxel size for viewpoint candidate grid (Paper Section 3.3.1)
    // Smaller = more candidates = better coverage but slower.
    // 10m gives ~50×40×7 = ~14K voxels before distance filtering.
    const float VOXEL_SIZE = 10.0f;

    // Maximum camera observation distance (metres).
    // Town01 is ~500 m wide; 200 m allows cross-street visibility.
    const float MAX_D = 200;

    // Ideal distance from sample point to camera
    const float BEST_DISTANCE = 30;

    // Paper Eq 2 / Eq 7 normal-view angle threshold. The paper does not
    // publish a value; 60 degrees is recorded as the baseline assumption.
    const float THETA_T = M_PI / 3.0f;

    // Paper-literal global scanned mark (Section 3.3.2) uses an FOV-radius
    // neighbourhood around the trigger sample. Set false for ray-visibility variant.
    const bool USE_PAPER_FOV_MARK = true;

    // --- Camera intrinsics ---
    // Matching the CARLA capture node defaults (1280×720, FOV 90°)
    const double RESOLUTION_H = 1280;
    const double RESOLUTION_V = 720;
    const double FOV_H        = 90;
    const double FOV_V        = 56.25;   // ≈ atan(720/1280 * tan(45°)) * 2, deg
}

#endif //FUXIAN_PARAMS_H
